blog/urls.py
from django.conf.urls import re_path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='detail'),
    re_path(r'^article/category/(?P<category_pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    # re_path(r'^categories/$', views.category, name='category'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.conf.urls import re_path
from . import views

app_name = 'comments'
urlpatterns = [
    re_path(r'^comment/post/(?P<article_pk>[0-9]+)/$', views.article_comment, name='article_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('分类', max_length=100)

    def __str__(self):
        return self.name

    '''
    class Meta:
        verbose_name='分类'
        verbose_name_plural='分类'
    '''


class Tag(models.Model):
    name = models.CharField('标签', max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    # 文章
    title = models.CharField('标题', max_length=70)
    cover = models.ImageField(upload_to='blog/cover', verbose_name='封面图', null=True, blank=True)  # 路径问题回头再试一试
    content = models.TextField('内容')
    publish_time = models.DateTimeField('发布日期')
    # 作者与分类的默认值为2和1,代表着相应数据库中id的字段,分别手动将其设置为了fengtianru117和未分类
    author = models.ForeignKey(User, default=2, on_delete=models.SET_DEFAULT, verbose_name='作者')
    category = models.ForeignKey(Category, default=1, on_delete=models.SET_DEFAULT, verbose_name='分类')
    tag = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='标签')
    views = models.PositiveIntegerField('阅读量', default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        # 使用update_fields只更新views字段,提高效率
        self.save(update_fields=['views'])

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from .models import Category, Article
from django.views.generic import ListView, DetailView
from comments.forms import CommentForm
from django.http import HttpResponse



class IndexView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'
    paginate_by = 6

    def get_queryset(self):
        article_list = super(IndexView, self).get_queryset().order_by('-publish_time')
        for a in article_list:
            a.content = markdown.markdown(a.content,
                                          extensions=[
                                              'markdown.extensions.extra',
                                              'markdown.extensions.codehilite',
                                              'markdown.extensions.toc',
                                          ])
        return article_list

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

'''def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.increase_views()
    article.content = markdown.markdown(article.content,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                        ])
    form = CommentForm()
    comment_list = article.comment_set.all()
    return render(request, 'blog/detail.html', context={
        'article': article,
        'form': form,
        'comment_list': comment_list,
    })'''


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        response = super(ArticleDetailView, self).get(request, *args, *kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        article = super(ArticleDetailView, self).get_object(queryset=None)
        article.content = markdown.markdown(article.content,
                                            extensions=[
                                                'markdown.extensions.extra',
                                                'markdown.extensions.codehilite',
                                                'markdown.extensions.toc',
                                            ])
        return article

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class CategoryView(IndexView):
    model = Article
    template_name = 'blog/article_list.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('category_pk'))
        article_list = super(CategoryView, self).get_queryset().filter(category=cate).order_by('-publish_time')
        for a in article_list:
            a.content = markdown.markdown(a.content,
                                          extensions=[
                                              'markdown.extensions.extra',
                                              'markdown.extensions.codehilite',
                                              'markdown.extensions.toc',
                                          ])
        return article_list

templates/blog/article_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="white-board ariticle-list">

                <ul class="category-nav">
                    {% get_article_categories as category_names %}
                    {% for category in category_names %}
                    <li>
                        <a class="on" href="{% url 'blog:category' category.pk %}">
                            {{category.name}}<span>&nbsp;{{category.counts}}&nbsp;</span>
                        </a>
                    </li>
                    {% endfor %}

                </ul>


                <script>
                    //选择当前浏览的话题
                    $(function () {
                        var category_id = $(".category-nav").attr("data-category-id");
                        $(".category-nav").find("a").each(function () {
                            var id = $(this).attr("href").split("/")[3];
                            if (id == category_id) {
                                $(this).addClass("on");
                            }
                        });
                    });
                </script>

                {% for article in article_list %}
                <article>
                    <div class="row">
                        <div class="col-lg-12 info">
                            <div class="title">
                                <a href=""></a>
                            </div>
                            <div class="abstract">
                                {{article.content|truncatechars_html:100|safe}}
                                <a href="">阅读全文 &gt;</a>
                            </div>
                            <div class="meta">
                                &nbsp;&nbsp; 分类:&nbsp;
                                <a href="">

                                </a>&emsp;话题:&nbsp;
                                <a href=""></a>&nbsp;
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}

                {% if is_paginated %}
                <div class="f-pagination">
                    {% if first %}
                    <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                    {% if left_has_more %}
                    <span>...</span>
                    {% endif %}
                    {% for i in left %}
                    <a href="?page={{i}}">{{i}}</a>
                    {% endfor %}
                    {% endif %}
                    <a class="current-page" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                    {% if right %}
                    {% for i in right %}
                    <a href="?page={{i}}">{{i}}</a>
                    {% endfor %}
                    {% if right_has_more %}
                    <span>···</span>
                    {% endif %}
                    {% endif %}
                    {% if last %}
                    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="white-board ariticle-detail">
                <div class="breadcrumb-nav">
                    <a href="/">首页</a> &gt;
                    <a href="#">文章</a> &gt;
                    <a href="#">
                        {{ article.category }}
                    </a>
                </div>
                <article>
                     {% if article.cover %}
                    <div class="cover">
                        <img src="{{ article.cover.url }}">
                    </div>
                    {% endif %}
                    <h1 class="title">{{article.title}}</h1>
                    <div class="meta">
                        {{ article.publish_time|date:"Y-m-d H:i:s" }} &emsp;{{ article.views }} 阅读&emsp;
                        <a href="#comment">
                            0 评论
                        </a>&emsp;分类:&nbsp;
                        <a href="{% url 'blog:category' article.category.pk %}">
                            {{ article.category }}
                        </a>&emsp;话题:&nbsp;{% for topic in article.topics.all %}
                        <a href="">{{ topic.name }}</a>&nbsp;{% endfor %}
                    </div>
                    <div class="content">
                        {{ article.content|safe }}
                    </div>
                </article>


                <div class="breadcrumb-nav">
                </div>
                <h1 class="title">评论:</h1>


                <article>
                    <form id="comment-form" action="{% url 'comments:article_comment' article.pk %}" method="post"
                          data-login-user="">
                        {% csrf_token %}
                        <div class="col-lg-8">
                            <label for="{{ form.name.id_for_label }}" style="width:100px">用户名：</label>
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                        <div class="col-lg-8">
                            <label for="{{ form.content.id_for_label }}" style="width:100px">内容：</label>
                            {{ form.content }}
                            {{ form.content.errors }}
                        </div>
                        <div class="submit">
                            <input type="submit" class="button" value="提交评论">
                        </div>

                    </form>
                </article>

                <div id='comment'>
                    <ul class="comment-list list-unstyled">
                        {% for comment in comment_list %}
                        <li class="comment">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date">{{ comment.create_time }}</time>
                            <div class="comment-item">
                                {{ comment.content }}
                            </div>
                            <div class="breadcrumb-nav">
                            </div>
                        </li>
                        {% empty %} 暂无评论 {% endfor %}
                    </ul>
                </div>


            </div>
        </div>
        <div class="col-lg-4">
            <div class="white-board widget">
                <h6 class="widget-title">分类</h6>
                <ul class="category-widget">
                    {% get_article_categories as article_categories %}
                    {% for category in article_categories %}
                    <li>
                        <a href="{% url 'blog:category' category.pk %}">
                            {{category.name}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
{% load blog_tags %}

<div class="container">
    <div class="row">
        <div class="col-lg-4 order-lg-2">
            <div class="white-board widget">
                <h6 class="widget-title">Fengtianru117</h6>
                <p><img src="{% static 'blog/images/Cartman.jpg' %}"></p>
                <ul class="social-list">
                    <li><a href="https://github.com/fengtianru117">
                        <i class="fa fa-github fa-2x"></i>
                    </a></li>
                    &nbsp;
                    <li><a href="https://www.zhihu.com/search?type=content&q=python">
                        <span class="fa-stack" style="margin-top: 0;">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-stack-1x" style="font-weight: bold; color: white;">知</i>
                    </span></a></li>
                </ul>
            </div>
            <div class="white-board widget">
                <h6 class="widget-title">分类</h6>
                <ul class="category-widget">
                    {% get_article_categories as article_categories %}
                    {% for category in article_categories %}
                    <li>
                        <a href="{% url 'blog:category' category.pk %}">
                            {{category.name}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="white-board widget">
                <h6 class="widget-title">标签</h6>
                <div class="topic-widget">
                    {% get_article_tags as article_tags %}
                    {% for tag in article_tags %}
                    <a href="#">
                        {{tag.name}}
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-lg-8 order-lg-1">
            <div class="white-board ariticle-list">
                <div class="list-title">最新文章</div>
                {% for article in article_list %}
                <article>
                    <div class="row">
                        {% if article.cover %}
                        <div class="col-lg-4 cover">
                            <div class="zoom-container flex-center">
                                <a href="{{ article.get_absolute_url }}">
                                    <img src="{{ article.cover.url }}">
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-8 info">
                            <div class="title">
                                <a href="{{article.get_absolute_url}}">{{article.title}}</a>
                            </div>
                            <div class="abstract">
                                {{article.content|truncatechars_html:100|safe}}
                                <a href="{{article.get_absolute_url}}">阅读全文 ></a>
                            </div>
                            <div class="meta">
                                {{article.publish_time|date:"Y-m-d H:i:s"}}&emsp;&ensp;{{article.views}}阅读&emsp;&ensp;分类:&nbsp;
                                <a href="{% url 'blog:category' article.category.pk %}">
                                    {{article.category}}
                                </a>&emsp;标签:&nbsp;
                                {%for tag in article.tag.all%}
                                <a href=" ">
                                    {{tag.name}}
                                </a>&nbsp;
                                {% endfor %}
                            </div>
                        </div>
                        {% else %}
                             <div class="col-lg-12 info">
                            <div class="title">
                                <a href="{{article.get_absolute_url}}">{{article.title}}</a>
                            </div>
                            <div class="abstract">
                                {{article.content|truncatechars_html:100|safe}}
                                <a href="{{article.get_absolute_url}}">阅读全文 ></a>
                            </div>
                            <div class="meta">
                                {{article.publish_time|date:"Y-m-d H:i:s"}}&emsp;&ensp;{{article.views}}阅读&emsp;&ensp;分类:&nbsp;
                                <a href="{% url 'blog:category' article.category.pk %}">
                                    {{article.category}}
                                </a>&emsp;标签:&nbsp;
                                {%for tag in article.tag.all%}
                                <a href=" ">
                                    {{tag.name}}
                                </a>&nbsp;
                                {% endfor %}
                            </div>
                        </div>

                        {% endif %}
                    </div>
                </article>
                {% empty %}
                还没有发布文章
                {% endfor %}
                <article>
                    <a href="{% url 'blog:category' 1 %}">更多文章 . . .</a>
                </article>
            </div>
        </div>
    </div>
</div>
{% endblock main %}