blog/urls.py
from django.conf.urls import re_path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='detail'),
    re_path(r'^article/category/(?P<category_pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    # re_path(r'^categories/$', views.category, name='category'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testrsa/urls.py
from django.conf.urls import re_path
from . import views

app_name = 'testrsa'
urlpatterns = [
    re_path(r'^testrsa$', views.testrsa, name='testrsa'),
    re_path(r'^encrypt$', views.encrypt, name='encrypt'),
]

testrsa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class PrivateKey(models.Model):
    n = models.TextField('n')
    e = models.TextField('e')
    d = models.TextField('d')
    p = models.TextField('p')
    q = models.TextField('q')

testrsa/views.py
from django.shortcuts import render
from .models import PrivateKey
from django.http import HttpResponse
import rsa


def testrsa(request):
    if request.method == 'GET':
        (public_key, private_key) = rsa.newkeys(512)
        key = PrivateKey(
            n=private_key.n,
            e=private_key.e,
            d=private_key.d,
            p=private_key.p,
            q=private_key.q,
        )
        key.save()
        return render(request, template_name='testrsa/testrsa.html', context={
            'public_key': public_key,
        })
    '''
    elif request.method == 'POST':
        crypto = request.POST.get('crypto')
        k = PrivateKey.objects.last()
        priv_key = rsa.PrivateKey(int(k.n), int(k.e), int(k.d), int(k.p), int(k.q))
        # ddd = rsa.decrypt(crypto, priv_key)
        return render(request, 'testrsa/test.html', context={
            'message': crypto,
        })
        '''


def encrypt(request):
    if request.method == 'POST':
        message = request.POST.get('message').encode('utf8')
        n = int(request.POST.get('N'))
        e = int(request.POST.get('E'))
        pub_key = rsa.PublicKey(n, e)
        k = PrivateKey.objects.last()
        priv_key = rsa.PrivateKey(int(k.n), int(k.e), int(k.d), int(k.p), int(k.q))
        crypto = rsa.encrypt(message, pub_key)  # crypto is a bytes tpye
        message = rsa.decrypt(crypto, priv_key).decode('utf8')
        return render(request, 'testrsa/encrypt.html', context={
            'crypto': crypto,
            'message': message,
        })
    else:
        return render(request, 'testrsa/encrypt.html', context={})

templates/testrsa/encrypt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>encrypt</title>
</head>
<body>
输入明文还有N和E会在下方返回加密后的密文和解密后的明文
<form id="testrsa" name="testrsa" method="post" action="{% url 'testrsa:encrypt' %}">
    {% csrf_token %}
    <textarea name="message" type="text" id="message" placeholder="请输入明文" ></textarea>
    <textarea name="N" type="text" id="N" placeholder="请输入N" required rows="20" cols="60"></textarea>
     <textarea name="E" type="text" id="E" placeholder="请输入E" ></textarea>
    <input type="submit" value="提交">
</form>
<br>加密后的密文是:
{% if crypto %}
<br>{{crypto}}
{% endif %}
<br>明文是:
{{message}}
</body>
</html>

templates/testrsa/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{message}}
</body>
</html>

templates/testrsa/testrsa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rsa</title>
</head>
<body>
<h4>随机生成了一个公钥！</h4>
<br>公钥的N为:{{public_key.n}}
<br>公钥的E为:{{public_key.e}}
<div>
    <br>进入加密页面可以加密解密 ——><a href="{% url 'testrsa:encrypt' %}" target="_blank">加密页面</a>
    <!--
<form id="testrsa" name="testrsa" method="post" action="{% url 'testrsa:testrsa' %}">
    {% csrf_token %}
    <textarea name="crypto" type="text" id="crypto" placeholder="请输入密文" required rows="20" cols="60"></textarea><input type="submit" value="提交">
</form>
-->
</div>
</body>
</html>