account/urls.py
from django.urls import re_path, path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'account'
urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    re_path(r'^login/$', views.OAuthLoginView.as_view(), name='login'),
    re_path(r'^oauth/github/$',views.GitHubOAuthView.as_view(),name='github_oauth'),
]

blog/urls.py
from django.conf.urls import re_path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='detail'),
    re_path(r'^article/category/(?P<category_pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    # re_path(r'^categories/$', views.category, name='category'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <title>fengtianru117的博客</title>
    <link rel="shortcut icon" href="images/favicon.ico">
    <meta name="description" content="Fossen's blog">
    <meta name="author" content="Fossen">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--
    <link href="https://cdn.bootcss.com/bootstrap/4.0.0-beta.3/css/bootstrap.css" rel="stylesheet">
    -->
    <link href="{% static 'blog/css/bootstrap.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet">
    <link href="http://apps.bdimg.com/libs/ueditor/1.4.3.1/third-party/SyntaxHighlighter/shCoreDefault.css"
          rel="stylesheet">
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0-beta.3/js/bootstrap.js"></script>
    <script src="http://apps.bdimg.com/libs/ueditor/1.4.3.1/third-party/SyntaxHighlighter/shCore.js"></script>
    <script src="{% static 'blog/js/common.js' %}"></script>
</head>

<body>
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand">
                    <div class="menu-toggle">≡</div>
                    <a class="logo" href="/">FENGTIANRU117</a>
                    <ul class="navbar-nav" id="menu">
                        <li>
                            <a href="/">首页</a>
                        </li>
                        <!--
                        <li>
                            <a href="sss">全部文章</a>

                        </li>
                        -->
                        {% get_article_categories as article_categories %}
                        <li>
                            <a href="{% url 'blog:category' 1 %}">分类</a>
                            <ul>
                                {% for category in article_categories %}
                                <li>
                                    <a href="{% url 'blog:category' category.pk %}">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <div class="tools">
                        <a></a>
                        <i class="fa fa-search fa-lg"></i>
                            <form method="get" action="/article/search/" id="search" >
                                <input name="q" type="text" maxlength='88' required placeholder="Search..." />
                            </form>
                        <div id="userbar">
                            {% if user.is_authenticated %}
                            <a class ="avatar"><img src="{{ user.profile.avatar }}" atl="avator"></a>
                             <a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                            <a href="/">{{ user.username }}</a>
                            <a href="{% url 'account:logout' %}?next={{ request.path }}">注销</a>
                            {% else %}
                            <a href="{% url 'account:login' %}?next={{ request.path }}">登录</a>

                            <a>注册</a>

                            {% endif %}

                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<main>
    {% block main %}
    {% endblock main %}
</main>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="copy-right">
                    <p>
                        <a href="#">Fengtianru117</a>©2018
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>

</html>